### ISSUE TITLE
Transpilation of Type Constraints is not working

### ISSUE THREAD

**Issue by ninmonkey** [StartAutomating/PipeScript#272]
I made one issue, so I don't spam issues when scattered examples fail

## Exceptions:

- [Transpilers/Parameters/ValidatePropertyName.psx.ps1](https://github.com/StartAutomating/PipeScript/blob/main/Transpilers/Parameters/ValidatePropertyName.psx.ps1)
- [ ] example and 3 of `PS 0.1.8`

## Env:
Pwsh 7.2, PS 0.1.8

## They have the same error

![image](https://user-images.githubusercontent.com/3892031/199264520-20a87b69-e19d-42f2-be28-a797fd17d933.png)
```cs
Microsoft.PowerShell.Commands.WriteErrorException: Command {
            param(
            [ValidatePropertyName(PropertyName='a','b')]
            [vfp]
            $InputObject
            )
            $InputObject
        } could not be transpiled into [ScriptBlock]s
Microsoft.PowerShell.Commands.WriteErrorException: : 2 error(s)
System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'Command'. The "  
        $PotentialCommand = $_
        if ($null -eq $PotentialCommand)         { return $false }
        if ($PotentialCommand -is [ScriptBlock]) { return $true }
        if ($PotentialCommand -is [string])      { return $true }
        if ($PotentialCommand -is [Management.Automation.CommandInfo]) { return $true }
        if ($PotentialCommand.GetType().Namespace -eq 'System.Management.Automation.Language' -and
            $PotentialCommand.GetType().Name -in 'AttributeAST', 'TypeExpressionAST','InvokeMemberExpressionAst') {       
            return $true
        }

        return $false
    " validation script for the argument with value "[vfp]" did not return a result of True. Determine why the validation 
script failed, and then try the command again.
 ---> System.Management.Automation.ValidationMetadataException: The "
        $PotentialCommand = $_
        if ($null -eq $PotentialCommand)         { return $false }
        if ($PotentialCommand -is [ScriptBlock]) { return $true }
        if ($PotentialCommand -is [string])      { return $true }
        if ($PotentialCommand -is [Management.Automation.CommandInfo]) { return $true }
        if ($PotentialCommand.GetType().Namespace -eq 'System.Management.Automation.Language' -and
            $PotentialCommand.GetType().Name -in 'AttributeAST', 'TypeExpressionAST','InvokeMemberExpressionAst') {       
            return $true
        }

        return $false
    " validation script for the argument with value "[vfp]" did not return a result of True. Determine why the validation 
script failed, and then try the command again.
   at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

**Comment by StartAutomating** [comment]
@ninmonkey what these two have in common is that they are using a "type constraint", rather than a full attribute.

This should be a valid scenario.

Making `[vfp]` `[vfp()]` should fix it, however things should also work in this scenario.
