### ISSUE TITLE
Fix Examples In Documentation

### ISSUE THREAD

**Issue by ninmonkey** [StartAutomating/PipeScript#423]
There's some examples that don't run. These closed the code-fence before the example ended.

Fixed or not, checklist:

- [x] OutFile
- [ ] [New-Pipescript](https://github.com/StartAutomating/PipeScript/blob/main/docs/New-PipeScript.md#example-3)

**Comment by ninmonkey** [comment]
## New-PipeScript with Help

I couldn't get [New-Pipescript 3 to work](https://github.com/StartAutomating/PipeScript/blob/main/docs/New-PipeScript.md#example-3>)

### Ex1: Docs

```ps1
impo pipeScript -PassThru

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.2.5                 pipeScript                          {Export-Pipescript, Get-PipeScript, Get-Transpiler, Import-PipeS… 

Pwsh 7.3.4> 
# from: <https://github.com/StartAutomating/PipeScript/blob/main/docs/New-PipeScript.md#example-3>
New-PipeScript -Parameter @{"bar"=@{
    Name = "foo"
    Help = 'Foobar'
    Attributes = "Mandatory","ValueFromPipelineByPropertyName"
    Aliases = "fubar"
    Type = "string"
}}
MetadataError: C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1:304:60
Line |
 304 |  …               if ($parameterMetadata.Help) { $parameterMetadata.Help}
     |                                                 ~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert the "Foobar" value of type "System.String" to type "System.Collections.IDictionary".


param(
[Parameter(Mandatory,ValueFromPipelineByPropertyName)]
[Alias('fubar')]
[String]
$foo
)
```

### Ex2: Tried a hashtable, it displays typename hashtable

Rns but writes `System.Collections.Hashtable` as help. What is the expected output? 

```ps1
New-PipeScript -Parameter @{"bar"=@{
    Name = "foo"
    Help = @{ 'bar' = 'help1' ; 'fubar' = 'help2' }    
    Attributes = "Mandatory","ValueFromPipelineByPropertyName"
    Aliases = "fubar"
    Type = "string"
}}


param(
# System.Collections.Hashtable
[Parameter(Mandatory,ValueFromPipelineByPropertyName)]
[Alias('fubar')]
[String]
$foo
)
```

**Comment by ninmonkey** [comment]
It occurs right here: [Commands/New-PipeScript.ps1#L303-L307](https://github.com/StartAutomating/PipeScript/blob/27c182228f5415f173428959d1c9afddb0eca161/Commands/New-PipeScript.ps1#L303-L307)

I couldn't figure out where the coercion is triggering off of the object property. It seems like that code is elsewhere. 

![image](https://github.com/StartAutomating/PipeScript/assets/3892031/08d7de1b-3df2-4e20-aff6-2b4bd5903495)


###  Error details

```ps1
New-PipeScript -Parameter @{"bar"=@{
    Name = "foo"
    Help = 'Foobar'
    Attributes = "Mandatory","ValueFromPipelineByPropertyName"
    Aliases = "fubar"
    Type = "string"
}}
```

```ps1
🐒 Pwsh 7.3.4>
$global:Error.Count           
1

🐒 Pwsh 7.3.4>
$global:Error | Get-Error | out-string | Set-Clipboard
```
```ps1
Exception             : 
    Type           : System.Management.Automation.ArgumentTransformationMetadataException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert the "Foobar" value of type "System.String" to type "System.Collections.IDictionary".
            HResult : -2146233087
        CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : RuntimeException
        InvocationInfo        : 
            ScriptLineNumber : 304
            OffsetInLine     : 60
            HistoryId        : -1
            ScriptName       : C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1
            Line             :                             if ($parameterMetadata.Help) { $parameterMetadata.Help}                            

            PositionMessage  : At C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1:304 char:60
                               + …               if ($parameterMetadata.Help) { $parameterMetadata.Help}
                               +                                                ~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands
            PSCommandPath    : C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at New-PipeScript<Process>, C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1: line 304
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     : 
        Name          : Transform
        DeclaringType : System.Management.Automation.ArgumentTypeConverterAttribute, System.Management.Automation, Version=7.3.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Cannot convert the "Foobar" value of type "System.String" to type "System.Collections.IDictionary".
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Type        : System.Management.Automation.PSInvalidCastException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert the "Foobar" value of type "System.String" to type "System.Collections.IDictionary".
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ConvertToFinalInvalidCastException
        TargetSite  : 
            Name          : ThrowInvalidCastException
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message     : Cannot convert the "Foobar" value of type "System.String" to type "System.Collections.IDictionary".
        Source      : System.Management.Automation
        HResult     : -2147467262
        StackTrace  : 
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     : 
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
   at System.Management.Automation.PSVariable.TransformValue(IEnumerable`1 attributes, Object value)
   at System.Management.Automation.PSVariable.SetValue(Object value)
   at System.Management.Automation.VariableOps.SetVariableValue(VariablePath variablePath, Object value, ExecutionContext executionContext, AttributeBaseAst[] attributeAsts)
   at System.Management.Automation.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
FullyQualifiedErrorId : RuntimeException
InvocationInfo        : 
    ScriptLineNumber : 304
    OffsetInLine     : 60
    HistoryId        : -1
    ScriptName       : C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1
    Line             :                             if ($parameterMetadata.Help) { $parameterMetadata.Help}                            

    PositionMessage  : At C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1:304 char:60
                       + …               if ($parameterMetadata.Help) { $parameterMetadata.Help}
                       +                                                ~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands
    PSCommandPath    : C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at New-PipeScript<Process>, C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\PipeScript\0.2.5\Commands\New-PipeScript.ps1: line 304
                        at <ScriptBlock>, <No file>: line 1


```
